spring:
  application:
    name: rabbitmq-tutorials
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost} # Usa la variable de entorno de Docker o localhost por defecto
    port: 5672
    username: guest
    password: guest

server:
  port: 8080